#!/bin/bash
#SBATCH --job-name=mothbot
#SBATCH --output=mothbot.out
#SBATCH --error=mothbot.err
#SBATCH --account JIGGINS-SL3-CPU
#SBATCH --partition cclake-himem
#SBATCH -t 00:10:00
#SBATCH --mem=12030
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mail-type=ALL

module purge
module load rhel7/default-gpu
module unload cuda/8.0
module load python/3.8 cuda/10.0 cudnn/7.5_cuda-10.0

source ./python_env/bin/activate
python ./network.py